<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Contracts\Contracts.csproj" />
      <ProjectReference Include="..\Persistence\Persistence.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="MassTransit.Abstractions">
        <HintPath>..\..\..\..\.nuget\packages\masstransit.abstractions\8.3.0\lib\net8.0\MassTransit.Abstractions.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
